version: "2"
services:
    prod:
        build: ./web
        container_name: vidl-server
        restart: always
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        command: npm run prod
        environment:
            - "NODEJS_VERSION=8.6.0"
            - "VIDL_ENV=prod"
    dev:
        build: ./web
        container_name: vidl-server
        restart: always
        ports:
            - 80:80
        volumes:
            - ./web/src:/usr/src/app
        command: npm run dev
        environment:
            - "NODEJS_VERSION=8.6.0"
            - "VIDL_ENV=dev"
